#!/usr/bin/env bash
##Check if argument is not provided
if [ -z "$1" ]; then
  echo "Argument not provided!"
else
  export VPC_ID="$1"
fi

##Check if argument is not provided
if [ -z "$2" ]; then
  echo "Argument not provided!"
else
  export IGW_ID="$2"
fi

##Check if argument is not provided
if [ -z "$3" ]; then
  echo "Argument not provided!"
else
  export SUBNET_ID="$3"
fi

##Check if argument is not provided
if [ -z "$4" ]; then
  echo "Argument not provided!"
else
  export RT_ID="$4"
fi


## detach IGW
aws ec2 detach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID

## delete IGW
aws ec2 delete-internet-gateway --internet-gateway-id $IGW_ID

## disassociate subnet
aws ec2 disassociate-route-table --association-id 123
## delete subnet
aws ec2 delete-subnet --subnet-id $SUBNET_ID

## delete route table
aws ec2 delete-route-table --route-table-id $RT_ID


## Delete VPC
aws ec2 delete-vpc --vpc-id $VPC_ID 