#!/usr/bin/env bash

echo "== delete bucket"

# Check bycket name
if [ -z "$1" ]; then
    echo "Digite o nome do bucket a ser deletado eg. ./bucket my-bucket-name"
    exit 1
fi

BUCKET_NAME=$1

aws s3api delete-bucket \
--bucket $BUCKET_NAME
