#!/usr/bin/env bash

echo "== deploy s3 bucket via CFN"

STAKE_NAME="cfn-simple-s3"

aws cloudformation deploy \
--template-file template.yaml \
--no-execute-changeset \
--region us-east-2 \
--stack-name $STAKE_NAME