AWSTemplateFormatVersion: "2010-09-09"
Description: "A simple s3 bucket"
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-overview.html#cfn-concepts-stacks
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: bucket-temp-1984